### ISSUE TITLE
not converting captcha into text

### ISSUE THREAD

**Issue by gaurav99t** [nekudo/decaptcha#1]
im tring this code but it is not converting captcha into text. 
im running this file decaptcha_solve.php 
database is also set

**Comment by gaurav99t** [comment]
i mean what data should be entered in the table decaptcha_templates ?
can you please share the data should be in this table?

**Comment by nekudo** [comment]
You have to train the script before it can solve anything. Use the decaptcha_solve.php
And please note: This is a 3 year old experimental project. If was never used in production. It is only intended to show how captcha-breaking CAN work.

**Comment by gaurav99t** [comment]
Not to worry
I fixed it already
